use_frameworks!

platform :ios, '11.0'

target 'VandMarvelAPI_Example' do
  pod 'VandMarvelAPI', :path => '../'

  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftHash'

  target 'VandMarvelAPI_Tests' do
    inherit! :search_paths

    
  end
end
